version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html
    overwrite: true

permissions:
  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 755
    type:
      - directory

  - object: /var/www/html
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file

hooks:
  AfterInstall:
    - location: scripts/build_and_push.sh
      timeout: 900
      runas: root
